"""
Django settings for dailyfresh project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 将 apps 插入到 python 搜索路径中,后面的 app 注册就不需要再添加 apps.路径,直接添加应用名就可以
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rrz4vg$lc^f&_qs*u=zeq)styxlfw9)od9)vt89j^w-+ui393v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'goods',
    'order',
    'user',
    'tinymce',  # 富文本编辑器
    'haystack',  # 全文检索框架
)

# django 认证系统使用的用户模型,AUTH_USER_MODEL 配置参数需要在第一次数据库迁移之前配置,否则 django 认证系统工作不正常
AUTH_USER_MODEL = 'user.User'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dailyfresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyfresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dailyfresh',
        'USER': 'root',
        'PASSWORD': 'mysql',
        'HOST': 'localhost',
        'PORT': 3306,

    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = '/var/www/dailyfresh/static'

# 富文本编辑器
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400,
}

# 配置发送邮箱
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# smtp 服务器地址,端口
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25
# 发送人的邮箱
EMAIL_HOST_USER = 'senglin75@163.com'
# 在邮箱设置中的客户端授权密码
EMAIL_HOST_PASSWORD = 'senglin75'
# 收件人看到的发件人
EMAIL_FROM = '天天生鲜<senglin75@163.com>'

# cache 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# redis 存储方式设置为使用 cache 存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 设置 login_require 装饰器重定向目标绝对路径
LOGIN_URL = '/user/login'  # 默认为 /acount/login

# 更改 Django 默认的文件存储类为自定义的 FDFSStorage 类
DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'

# client_conf 的文件默认搜索路径
CLIENT_CONF = './utils/fdfs/client.conf'

# nginx 的默认域名和端口号
FDFS_PATH = 'http://192.168.1.5:8888/'

# 全文检索框架的配置
HAYSTACK_CONNECTIONS = {
    'default': {
        # 使用 whoosh 引擎
        # 'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # 配合 jieba 来对中文分词能力进行提高
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',
        # 文件搜索路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index')
    }
}

# 当添加、更新、删除数据库时,自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# 设置搜索结果一页显示多少内容
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 1